# Site settings
title: Frankie Cook
email: nfcook@pm.me
description: > # this means to ignore newlines until "baseurl:"
baseurl: "nfcook.github.io" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: frankiefrankie
github_username: frankiecook

# Build settings
markdown: kramdown
