# Site settings
title: Frankie Cook
email: nfcook@pm.me
description: > # this means to ignore newlines until "baseurl:"
# baseurl: "nfcook.github.io" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: frankiefrankie
github_username: frankiecook
linkedin_url: https://www.linkedin.com/in/frankie-cook-142164164/

# Build settings
markdown: kramdown

# header
header_title: Hi, my name is Frankie Cook.
header_description: I code things into life.

# about
about_title: Louisiana Tech University 2024 Alumni
about_description: I am a nerd from Louisiana who found a passion in Computer Science, which propelled me to graduate from LA Tech University.

# services
service_title: Forever an Imperfect Perfectionist
service01_title: Programming Teacher
service01_description: Avalable to teach 1-on-1 programming and computer science lessons
service02_title: FrankieFrankie.xyz
service02_description: "FrankieFrankie.xyz is my first website and holds many of my personal web-projects"
service03_title: Languages
service03_description: Python, Java, C/C++, HTML, JavaScrip, CSS, TypeScript, and SQL
service04_title: Software
service04_description: Raspberry Pi, Materials Studio, FABRIC, Google Colab, Solidworks, MATLAB, COMSOL, Arduino, UML

# contact
contact_title: Let's Get In Touch!

# Portfolio Information
project01_name: Jekyll Website
project01_category: Web Development
project01_date: May 30, 2024
project01_imgs: NFCook-Folio.png
project01_img: NFCook-Folio-Demo.gif
project01_description: "Hey, the very website you’re on right now! Jekyll is a framework for building web projects and generates static sites using Ruby. I was able to get my website hosted through Netlify and Github.
"

project02_name: Axolotl
project02_category: Cyber Security
project02_date: Feb. 24, 2024
project02_imgs: Axolotl-Folio.png
project02_img: Axolotl-Folio-Demo.gif
project02_description: "A cyber security challenge where the programmer is tasked with locating information concerning the whereabouts of their stolen dog. Organized into three levels it encourages the user to dig through a file system that contains some useful c files, a key, and a pygame application.
"

project03_name: Selk
project03_category: Game Development
project03_date: Feb. 20, 2024
project03_imgs: Selk-Folio.png
project03_img: Selk-Folio-Demo.gif
project03_description: "A sci-fi game set inside a bio-dome on Titan that challenges the player to solve puzzles, but our focus was always on exploring a colorful and vibrant environment. I primarily focused on landscape design, environment design, modeling, and character animation.
"

project04_name: Dijkstra’s Implementation
project04_category: Computer Networks
project04_date: February 18, 2024
project04_imgs: Dijkstra-Folio.png
project04_img: Dijkstra-Folio-Demo.gif
project04_description: "Implementation of Dijkstra’s algorithm to compute the shortest path tree for given topology data. Topology data and nodes are stored as a spreadsheet.
"

project05_name: Ray-tracing Engine
project05_category: Game Development
project05_date: Feb. 17, 2024
project05_imgs: Raytracing-Folio.png
project05_img: Raytracing-Folio-Demo.gif
project05_description: "Python engine capable of rendering spheres and planes, as well as calculating reflective and refractive rays. Includes settings for maximum view distance and number of recursive reflections.
"

project06_name: Graphics Engine
project06_category: Game Development
project06_date: Jan. 22, 2024
project06_imgs: 3D-Engine-Folio.png
project06_img: 3D-Engine-Folio-Demo.gif
project06_description: "Python engine capable of rending objects, such as pyramids, boxes, and cylinders. Transformations can be applied to the current object, such as rotation, scaling, translation, and a reset option. Most impressive are the five render and shading modes available: wire-frame, polygon fill, flat shading, Gouraud shading, and Phong shading.
"

project07_name: Google Cloud Computing
project07_category: Cyber Security
project07_date: Nov. 17, 2023
project07_imgs: Google-Cloud-Folio.png
project07_img: Google-Cloud-Folio-Demo.gif
project07_description: "Spent a course operating in Google Cloud, where I learned about Kubernetes, Pub/Sub events, App Engine, autoscalling, NoSQL databases, routing tables, load balancing, and more.
"

project08_name: Horse Health Prediction
project08_category: Data Mining
project08_date: Nov. 16, 2023
project08_imgs: Horse-Health-Folio.png
project08_img: Horse-Health-Folio-Demo.gif
project08_description: "Sifted through a dataset containing horse veterinarian records to gather any meaningful correlations. Operated in Google Colab and used Pandas, Numpy, and Seaborn to develop software that could analyze 300 horse records.
"

project09_name: Cyberstorm
project09_category: Cyber Security
project09_date: Nov. 10, 2023
project09_imgs: Cyberstorm-Folio.png
project09_img: Cyberstorm-Folio-Demo.gif
project09_description: "A cyber security event where teams competed against each other in a race for the most points. Useful programs we used were a binary encoder/decoder, a Vigenere cipher, a covert ftp channel, a timelock program, an XOR crypto method, and a steganography program.
"

project10_name: Canvas / Gallery
project10_category: Web Application
project10_date: Aug. 25, 2023
project10_imgs: Canvas-Gallery-Folio.png
project10_img: Canvas-Gallery-Folio-Demo.gif
project10_description: "Canvas & Gallery serve an interconnected function as a web application. The Canvas allows visitors to draw anything they wish, and, once finished, users can submit to the Gallery. In the Gallery, every image from the database is displayed, which in turn showcases the user’s artwork.
"

project11_name: Guestbook
project11_category: Web Application
project11_date: Aug. 11, 2023
project11_imgs: Guestbook-Folio.png
project11_img: Guestbook-Folio-Demo.gif
project11_description: "Guestbook prompts the user for their email, name, and comment and saves this information to a database. Just below the submission, all signatures are displayed.
"

project12_name: P3DE
project12_category: Web Game Development
project12_date: July 3, 2023
project12_imgs: P3DE-Folio.png
project12_img: P3DE-Folio-Demo.gif
project12_description: "An earnest attempt at recreating the original ray casting engines from the 90s. No goal exists, but you do load into a demo room with textures, animated textures, and the player has a weapon that destroys walls.
"

project13_name: StupidDuck
project13_category: Web Game Development
project13_date: Jan. 24, 2023
project13_imgs: StupidDuck-Folio.png
project13_img: StupidDuck-Folio-Demo.gif
project13_description: "An impressive 2D web-engine for a silly game that was built from scratch following Vronman’s incredible tutorial. A boundless amount was learned about game engines and how developers tackle solutions. I found myself making more buses than city transit, stepping through animation control, and calculating transformations for objects.
"

project14_name: Kill the Phish
project14_category: Web Application
project14_date: Apr. 23, 2021
project14_imgs: Kill-the-Phish-Folio.png
project14_img: Kill-the-Phish-Folio-Demo.gif
project14_description: "A Google Chrome plugin that detects and warns users of malicious links. Our team learned how to implement modern design strategies, such as Waterfall, Agile, Scrum, Kanban, UML diagrams, class diagrams, object oriented design patterns, and debugging/profiling.
"

project15_name: Car Rental Service
project15_category: Database Management
project15_date: Feb. 27, 2021
project15_imgs: Car-Rental-Folio.png
project15_img: Car-Rental-Folio-Demo.gif
project15_description: "Designed and implemented a database that acts for a car rental scenario using DDL commands, DML commands, triggers, views, and schema modification. Created an enhanced entity-relationship (EER) diagram and a relational schema diagram in MySQL Workbench Models.
"

project16_name: Quantum Computer Architecture
project16_category: Research
project16_date: Feb. 2, 2021
project16_imgs: Quantum-Architecture-Folio.png
project16_img: Quantum-Architecture-Folio-Demo.gif
project16_description: "Researched and presented about the state of quantum computer architecture. Covered topics such as how these devices are implemented through trapping ions and confining electrons.
"

project17_name: Sand Simulator
project17_category: Web Game Development
project17_date: Dec. 26, 2020
project17_imgs: Sand-Simulator-Folio.png
project17_img: Sand-Simulator-Folio-Demo.gif
project17_description: "A very simplified 2D physics engine that simulates sand falling. Grains of sand rain down from the sky as pixels, which you can control the direction of.
"

project18_name: Cherry Game
project18_category: Game Development
project18_date: Oct. 23, 2020
project18_imgs: Cherry-Game-Folio.png
project18_img: Cherry-Game-Folio-Demo.gif
project18_description: "An RPG developed in C# using a Visual Studios framework. From the onset this project was focused on implementing software design strategies, such as Waterfall, Agile, Scrum, Kanban, UML diagrams, class diagrams, and more.
"

project19_name: Non-deterministic Automata
project19_category: Research
project19_date: Nov. 18, 2020
project19_imgs: Automata-Folio.png
project19_img: Automata-Folio-Demo.gif
project19_description: "Researched and presented on the limitations of non-deterministic finite automata imposed by a one letter input alphabet. Cover the theorems and proofs for 'unreachable configurations' and
'unreachable configurations of fixed size.'
"

project20_name: Embedded Operating Systems
project20_category: Research
project20_date: May 14, 2020
project20_imgs: Embedded-OS-Folio.png
project20_img: Embedded-OS-Folio-Demo.gif
project20_description: "Research paper and final presentation that covered the history, applications, current state, advantages and disadvantages of embedded operating systems.
"

project21_name: Eternal Knight
project21_category: Game Development
project21_date: May 11, 2019
project21_imgs: Eternal-Knight-Folio.png
project21_img: Eternal-Knight-Folio-Demo.gif
project21_description: "Participated in a 48-hour video game competition where I served as the composer on our team of three. Remarkably, our project swiped 1st place.
"

project22_name: Pi Sonar
project22_category: Raspberry Pi
project22_date: Nov. 3, 2019
project22_imgs: Pi-Sonar-Folio.png
project22_img: Pi-Sonar-Folio-Demo.gif
project22_description: "Created a sonar device by combining a Raspberry Pi, digital servo, rotary connector, and an ultrasonic sensor. Our sonar rotated 360 degrees while emitting ultrasonic rays, and, using distance calculations, could plot a 2D representation of the environment.
"

project23_name: Room Adventure
project23_category: Raspberry Pi
project23_date: Jul. 24, 2019
project23_imgs: Room-Adventure-Folio.png
project23_img: Room-Adventure-Folio-Demo.gif
project23_description: "Final project for a year long course in Python that challenged students to create a text-based adventure game. Created graphics and a user interface that could display text and receive input.
"

# project_name: 
# project_category: 
# project_date: 
# project_img: 
# project_description: "
# "
